### ISSUE TITLE
Upload stuck when use reverse proxy 

### ISSUE THREAD

**Issue by cyoki** [timvisee/send-docker-compose#13]
My Send-Docker is currently deployed on a machine with the IP address 192.168.1.10. I'm trying to enable port forwarding in the router to access the machine using the URL like `example.com`.

After configuring the port forwarding, logging in and uploading files using the `host:port` format in the URL, everything works as intended. However, when I map the `host:port` to the reverse proxy URL like `send.example.com` and try to log in using the URL `send.example.com`, the upload process gets stuck as below.

![image](https://github.com/timvisee/send-docker-compose/assets/17739163/a4679e61-e8f3-4a88-9ef4-43b91bd8e7b0)

By the way, I didn't find VIRTUAL_HOST and VIRTUAL PORT in the [config.js](https://github.com/timvisee/send/blob/master/server/config.js), but in the [example compose file](https://github.com/timvisee/send-docker-compose), it has. 

May I ask how to write compose file in this situation? Thanks!

**Comment by cyoki** [comment]
OK, I have figured it out, we need to add websocket:

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";

**Comment by Technically-Possible** [comment]
Could you explain this in more detail I'm having the same issues
