### ISSUE TITLE
Failed to upload after at 98% upload

### ISSUE THREAD

**Issue by Ciros55** [timvisee/send-docker-compose#6]
Error: connection closed at WebSocket.i (api.js:167:14)

This only happened when I use reverse proxy , using local ip its fine.

**Comment by Ciros55** [comment]
i did enabled WebSocket support
![2022-04-09_23-47](https://user-images.githubusercontent.com/75262274/162583466-99bb44a9-f9d5-4f24-abd1-658eee60deb8.png)

**Comment by Ciros55** [comment]
Nevermind. I managed to solve this issue by enabling HSTS and it worked.

**Comment by timvisee** [comment]
Not sure what happened, but yes, websocket support must be enabled as that's used for file uploads.

You mention that HSTS solved the issue. That shouldn't have any effect on websocket connectivity though. Or did you have certificate validation issues?

**Comment by Ciros55** [comment]
I tired 2 certificate CloudFlare Origin , Let Encrypt. both fails to upload until HSTS enabled. 
the Reverse Proxy I used is Nginx Proxy Manager (Current), HAProxy (No longer using but has same error.).

**Comment by Ciros55** [comment]
After messing around on CloudFlare
It also could be CloudFlare Always on HTTPS messing with it.
I disabled HSTS and CloudFlare Always on HTTPS. It works just fine.
![image](https://user-images.githubusercontent.com/75262274/162789760-625e97d9-76b3-40ec-b823-af57edce5080.png)

**Comment by timvisee** [comment]
That definitely sounds like it could mess with uploads. Happy to see you fixed the issue.
