### ISSUE TITLE
(Feature Request) Please make the Dockerfile available on the main ffsend repo, or allow 'urlshorten' env.

### ISSUE THREAD

**Issue by HrBingR** [timvisee/send-docker-compose#7]
Good day,

I would love to have the Dockerfile to be able to build my own version of the image compiled with the "urlshorten" cargo flag to make shorter URLs from ffsend. 

I understand that an env of this is very unlikely if this flag needs specifying at runtime, in which case having the Dockerfile available in the main ffsend repo (so that all of the dependencies are in the same place, but having the Dockerfile here could work too) would allow docker users to customize compile flags/features for themselves, and also gain access to the urlshorten flag rather than having to build and install the non-docker version.

**Comment by timvisee** [comment]
This repository is for [Send](https://github.com/timvisee/send), not [`ffsend`](https://github.com/timvisee/ffsend).

The Dockerfile that is used for `ffsend` is located [here](https://github.com/timvisee/ffsend/blob/master/pkg/docker/Dockerfile), though it requires building ffsend externally.

The publicly available image should have `urlshorten` enabled. Check it out [here](https://github.com/timvisee/ffsend/#docker-image).

Hope that helps!
