### ISSUE TITLE
gc.cron clean-up files that expire less than a day

### ISSUE THREAD

**Issue by aniston** [timvisee/send-docker-compose#9]
HI , i need some cron help here. Running my own docker instance based on the send-docker-compose and saving files locally with the 10m, 1h, 1d, 7d, 30d intervals. Hence using gc.cron to do the clean-up after expiry.

Given that ..
> Uploads have their lifetime in days prefixed

I noticed that files uploaded for expiry set to 10 minutes or less than a day they still get the lowest prefix of `1-`, using the example gc.cron i cannot find a way to differentiate between 10m and 1h files from the `find -name` method

the best i could come up with is
- `0 * * * * find /root/send/uploads/ -name 1-\* -mmin +90 -exec rm {} \;`
that gets rid of 1h expirxy files every 90m and should also clean-up those with lower expiry times as this runs every cron hour.

anyone know how to get around this with a combination options of `-mmin -N` and `-mmin +N`  to be able to clean-up files with the 10m and 1h expiry

and yes thanks @timvisee for keeping the Firefox Send fork going.

**Comment by timvisee** [comment]
There is no way to differentiate between them. You should therefore consider all uploads having `-1` to have an expiry time of 1 day.

That means that it takes a little longer for 10 minute files to be removed. That doesn't mean users can still download it, so this isn't a security concern.

Therefore just use:

```cron
0 * * * * find /var/lib/send/uploads/ -name 1-\* -mmin +1500 -exec rm {} \;
```

Hope that helps!

**Comment by tarbib** [comment]
@timvisee Hello !
I'm not sure to understand how the file gc.cron should be used. I use send with S3 storage and currently my 1 hour expiry file was not removed from the bucket.
Should I docker exec in the container then "crontab -e" there and save the line 
`0 * * * * find /var/lib/send/uploads/ -name 1-\* -mmin +1500 -exec rm {} \;`
Or should I execute the file somehow ?
Thanks

**Comment by timvisee** [comment]
Hi @tarbib! The `gc.cron` file is intended for when you're storing files on your local disk without S3.

When using S3 I recommend to configure a lifecycle configuration instead. When doing so, the S3 server itself will take care of periodically deleting old files.

You can find an example of such configuration here: https://github.com/timvisee/send/blob/master/s3-lifecycle-example.xml

Here's documentation on how to actually apply it: https://docs.aws.amazon.com/AmazonS3/latest/userguide/how-to-set-lifecycle-configuration-intro.html

**Comment by tarbib** [comment]
@timvisee thanks a lot for your quick answer! Very appreciated. I will have a look.

Out of curiosity how do you use the `gc.cron` for fields on local disks? With the contab -e command within the container or there's another way from the host?

**Comment by timvisee** [comment]
> Out of curiosity how do you use the gc.cron for fields on local disks? With the contab -e command within the container or there's another way from the host?

Yeah you'd probably use it on the host itself. As crons within the container are not persisted.
